<?php

use TestTask\Model\Comment;

/**
 * @var $message string
 * @var $comment Comment
 * @var $token string
 */

?>

<?php if ($message): ?>
    <div class="alert alert-warning">
        <?= $message ?>
    </div>
<?php endif; ?>

<form class="form-signin" method="POST" action="/edit?id=<?= $comment->id ?>">
    <label for="name">Name</label>
    <input class="form-control" type="text" name="name" value="<?= $comment->name ?>">

    <br>
    <label for="name">Email</label>
    <input class="form-control" type="text" name="email" value="<?= $comment->email ?>">

    <br>
    <label for="name">Content</label>
    <textarea class="form-control" name="content"><?= $comment->content ?></textarea>

    <input type="hidden" name="token" value="<?= $token ?>">

    <br>

    <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
</form>
