<?php

/**
 * @var $message string
 * @var $token string
 * @var $login string
 * @var $password string
 */

?>

<?php if ($message): ?>
<div class="alert alert-warning">
    <?= $message ?>
</div>
<?php endif; ?>

<form class="form-signin" method="POST" action="/admin/login">
    <h2 class="form-signin-heading">Sign in as Admin</h2>
    <label for="inputEmail" class="sr-only">Login</label>
    <input name="login" type="text" id="inputEmail" class="form-control" placeholder="Login" required="" autofocus="" value="<?= $login ?>">
    <br>
    <label for="inputPassword" class="sr-only">Password</label>
    <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required="" value="<?= $password ?>">
    <br>
    <input type="hidden" name="token" value="<?= $token ?>">
    <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
</form>
