<?php

use TestTask\Model\Admin;

/**
 * @var $view_content string
 */

?>

<html>
<head>
    <title>Test task</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="masthead">
            <h3 class="text-muted">Test task</h3>
            <nav>
                <ul class="nav nav-justified">
                    <li class="active"><a href="/">Comments</a></li>
                    <?php if (!Admin::isLogined()): ?>
                        <li><a href="/admin/login">Login as admin</a></li>
                    <?php else: ?>
                        <li><a href="/admin/logout">Logout</a></li>
                    <?php endif; ?>
                </ul>
            </nav>
        </div>

        <?= $view_content ?>

    </div>
</div>
<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<?php if (isset($line_scripts)) echo "<script>$line_scripts</script>" ?>

</body>
</html>
